language: ruby
rvm:
  - 1.9.3
env:
  global:
    secure: YkpPL5PyKjk4mV+OvVN9cDU41I7NGNuiBYop2dfx3fqPRdbaFZD8JEaMNK3CBUL8NaEDP8k1NNclg9QAXpyFLHXZ65Q1vg+CmSePfUxZO84NnFKRFNlWm3QBPMe3ke9hYfPbR0C3O9mMjOlHWjTTrBOV3CICWRJMgOESlVUQNksuhA0yrkdi/56wvsEYL7/Pj4RZc/67AqBCu7ziyXPWLrYdHbPXf8qsF6rag7sQdJ4U99lZu2DOF3IySE+lef10YRc2ChcSfOeQnwOAoFp4+TtcRyuijt6azzZ3CSt3qPRt5Xif1enjX3kBpxWZpNpQ9B3dcel8GKal0x+N2qHjfdLCcs73Iz+GO8/5Gaan0CxW95DgDA7ZH3onHzLE+iCuHOXDMbUxVjwT6ROop4Owl6UlsSr3MP6DK3e8yIAOJtcvVZ1iqc62XSlIWi/a1N0fcVvBKxhSYaQGrhhWSzmmeD/YOU9K4IKewQyHIetrGy4jVYXqTgD7s1eyr0rWDsFbori2TJRvkEGkbxmEcxxSUOWumXELXxuFbynNqVL5R/AJv3b31fjylDjmGxML9hhUSnOqWhuC9tnlRxGVdgRrtXAHFLzWwD29vDWUisny+B0n/cytYC+vCAo8mBp/yeyg9HRVhJ77U0SI7Jia6mqu3ClU+WsdP7yAw23qxwlVcmA=
